<h1><p style="text-align: center;">NumPy Lesson, Session - 2</p><h1>

# NumPy Indexing and Selection

In this lecture we will discuss how to select elements or groups of elements from an array.

In [4]:
import numpy as np

In [10]:
#  creating sample array
arr = np.arange(0,11)

# show arr (if you write only arr jupyter gives you also the type of arr)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [11]:
# show arr (if you print arr you can't see the type of arr)
print(arr)

[ 0  1  2  3  4  5  6  7  8  9 10]


## Bracket Indexing and Selection
The simplest way to pick one or some elements of an array looks very similar to python lists:

In [13]:
# get a value at an index
arr[8]

8

In [14]:
# negative indexing works like in python lists
arr[-1]

10

In [15]:
#  get values in a range
arr[1:5]

array([1, 2, 3, 4])

In [16]:
#  get values in a range
arr[:5]

array([0, 1, 2, 3, 4])

In [17]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [18]:
# arr[start:stop:step], odds
arr[1::2]

array([1, 3, 5, 7, 9])

In [19]:
# arr[start:stop:step], evens
arr[0::2]

array([ 0,  2,  4,  6,  8, 10])

## Indexing a 2D array (matrices)

<p>The general format is <b>arr_2d[row][col]</b> or <b>arr_2d[row,col]</b>. I recommend usually using the comma notation for clarity.</p>

In [20]:
arr_2d=np.array([[5,10,15],[20,25,30],[35,40,45]])

#Show
arr_2d

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [21]:
#Indexing row
arr_2d[1]

array([20, 25, 30])

In [22]:
# Format is arr_2d[row][col] or arr_2d[row,col]

# Getting individual element value
arr_2d[1][2]

30

In [23]:
# Getting individual element value
arr_2d[2,1]

40

In [24]:
arr_2d

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [25]:
# 2D array slicing

# Shape (2,2) from top right corner
arr_2d[0:2,1:]

array([[10, 15],
       [25, 30]])

In [26]:
# Shape bottom row
arr_2d[2]

array([35, 40, 45])

In [27]:
#Shape bottom row
arr_2d[2,:]

array([35, 40, 45])

In [28]:
# Middle column
arr_2d[:,1]

array([10, 25, 40])

In [29]:
arr_2d

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [30]:
# The very right column
arr_2d[:,2]

array([15, 30, 45])

In [31]:
# let's convert 25 to 99
arr_2d[1,1]=99
arr_2d

array([[ 5, 10, 15],
       [20, 99, 30],
       [35, 40, 45]])

In [32]:
# default dtype is int. take a look at the assigning of the float value
arr_2d[1][1]=7.7
arr_2d

array([[ 5, 10, 15],
       [20,  7, 30],
       [35, 40, 45]])

### Fancy Indexing

Fancy indexing allows you to select entire rows or columns out of order,to show this, let's quickly build out a numpy array:

In [33]:
v=np.arange(0,30,3)
v

array([ 0,  3,  6,  9, 12, 15, 18, 21, 24, 27])

In [34]:
v[1]

3

In [35]:
v[3]

9

In [36]:
v[7]

21

In [39]:
# we can select separate elements using their indices in a list
index_list=[1,3,7]
v[index_list]

array([ 3,  9, 21])

In [41]:
v[[1,3,7]]

array([ 3,  9, 21])

In [44]:
# Set up matrix
arr2d=np.zeros((10,10),dtype=int)
arr2d

array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0]])

In [45]:
arr2d.shape

(10, 10)

In [46]:
# Length of array
length_arr=arr2d.shape[0]
length_arr

10

In [47]:
arr2d[0]

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [48]:
arr2d[3]

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [49]:
#Set up array
for i in range(length_arr):
    arr2d[i]=i
    
arr2d

array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [2, 2, 2, 2, 2, 2, 2, 2, 2, 2],
       [3, 3, 3, 3, 3, 3, 3, 3, 3, 3],
       [4, 4, 4, 4, 4, 4, 4, 4, 4, 4],
       [5, 5, 5, 5, 5, 5, 5, 5, 5, 5],
       [6, 6, 6, 6, 6, 6, 6, 6, 6, 6],
       [7, 7, 7, 7, 7, 7, 7, 7, 7, 7],
       [8, 8, 8, 8, 8, 8, 8, 8, 8, 8],
       [9, 9, 9, 9, 9, 9, 9, 9, 9, 9]])

In [50]:
# we can select separate rows by indices in a list
arr2d[[2,4,6,8]]

array([[2, 2, 2, 2, 2, 2, 2, 2, 2, 2],
       [4, 4, 4, 4, 4, 4, 4, 4, 4, 4],
       [6, 6, 6, 6, 6, 6, 6, 6, 6, 6],
       [8, 8, 8, 8, 8, 8, 8, 8, 8, 8]])

In [51]:
# Allows in any order
arr2d[[6,4,2,7]]

array([[6, 6, 6, 6, 6, 6, 6, 6, 6, 6],
       [4, 4, 4, 4, 4, 4, 4, 4, 4, 4],
       [2, 2, 2, 2, 2, 2, 2, 2, 2, 2],
       [7, 7, 7, 7, 7, 7, 7, 7, 7, 7]])

<h3>any_array[[row indices], [column indices]]</h3>

In [52]:
jj=np.arange(1,17).reshape(4,4)

In [53]:
jj

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [54]:
# let's select separate values of 5 and 12
# row 1 and column 0. row 2 and column 3. 
jj[[1,2],[0,3]]

array([ 5, 12])

In [55]:
# this time let's select separate values of 1, 10 and 16
jj[[0,2,3],[0,1,3]]

array([ 1, 10, 16])

### Using ***basic index*** and ***fancy index*** together

In [56]:
jj

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [57]:
# let's select 6 and 8 which are in the same row (index 1)
jj[1,[1,3]]

array([6, 8])

In [58]:
# let's select 2 and 14 which are the same column (index 1)
jj[[0,3],1]

array([ 2, 14])

### Using ***basic slicing*** and ***fancy index*** together

In [59]:
jj

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [60]:
# let's select two middle columns
jj[:,[1,2]]

array([[ 2,  3],
       [ 6,  7],
       [10, 11],
       [14, 15]])

In [67]:
# let's select center small square (4 elements)
jj[1:3,[1,2]]

array([[ 6,  7],
       [10, 11]])

In [66]:
# let's select center small square (6 elements)
jj[1:3,[1,2,3]]

array([[ 6,  7,  8],
       [10, 11, 12]])

In [64]:
# remember, how normal slicing is executed
jj[1:3,1:3]

array([[ 6,  7],
       [10, 11]])

## More Indexing Help
Indexing a 2d matrix can be a bit confusing at first, especially when you start to add in step size. Try google image searching NumPy indexing to find useful images.

# Selection on a Condition

Let's briefly go over how to use brackets for selection based off of comparison operators.

In [68]:
arr=np.arange(1,11)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [69]:
arr>4

array([False, False, False, False,  True,  True,  True,  True,  True,
        True])

In [70]:
bool_arr=arr>4

In [71]:
arr[bool_arr]

array([ 5,  6,  7,  8,  9, 10])

In [72]:
arr[arr<6]

array([1, 2, 3, 4, 5])

In [73]:
arr[arr>2]

array([ 3,  4,  5,  6,  7,  8,  9, 10])

In [74]:
# and ==> &
arr[(arr!=3) & (arr!=4)]

array([ 1,  2,  5,  6,  7,  8,  9, 10])

In [75]:
# if you want you can use if_statement and for_loop

# Broadcasting

Numpy arrays differ from a normal Python list because of their ability to broadcast:

https://numpy.org/doc/stable/user/theory.broadcasting.html

In [76]:
#Setting a value with index range (Broadcasting)
arr[:5]=77
#Show
arr

array([77, 77, 77, 77, 77,  6,  7,  8,  9, 10])

In [77]:
a=[0,2,4,6,8,10]

In [78]:
# a[0:3] = 100 Error raises

In [79]:
a[:3]=[100,100,100]
a

[100, 100, 100, 6, 8, 10]

In [80]:
# Reset array, we'll see why I had to reset in  a moment
arr=np.arange(0,11)

# Show
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [81]:
# Important notes on Slices
slice_of_arr=arr[0:6]

# Show slice
slice_of_arr

array([0, 1, 2, 3, 4, 5])

In [82]:
#Change Slice
slice_of_arr[:]=99

#Show Slice again
slice_of_arr

array([99, 99, 99, 99, 99, 99])

In [83]:
arr

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

In [84]:
#To get a copy, need to be explicit
arr_copy=arr.copy()
arr_copy

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

In [85]:
# We can assign a list of values in an exact dimension
arr_copy[:6]=[0,1,2,3,4,5]

In [86]:
arr_copy

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [87]:
arr

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

# NumPy Operations

## Arithmetic Operations

#### You can easily perform array with array arithmetic, or scalar with array arithmetic.

In [89]:
arr = np.arange(0,10)

In [90]:
arr+arr

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [91]:
arr*arr

array([ 0,  1,  4,  9, 16, 25, 36, 49, 64, 81])

In [92]:
arr-arr

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [93]:
import warnings
warnings.filterwarnings('ignore')

In [94]:
# Warning on division by zero, but not an error!
# Just replaced with nan
arr / arr

array([nan,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.])

In [95]:
# Also warning, but not an error instead infinity
1/arr

array([       inf, 1.        , 0.5       , 0.33333333, 0.25      ,
       0.2       , 0.16666667, 0.14285714, 0.125     , 0.11111111])

In [96]:
arr**2

array([ 0,  1,  4,  9, 16, 25, 36, 49, 64, 81])

In [97]:
v=np.array([1,2,3,4,5])
v

array([1, 2, 3, 4, 5])

In [98]:
v-2

array([-1,  0,  1,  2,  3])

In [99]:
v*10

array([10, 20, 30, 40, 50])

In [100]:
v*5/10-1

array([-0.5,  0. ,  0.5,  1. ,  1.5])

## Universal Array Functions

#### Numpy comes with many [universal array functions](http://docs.scipy.org/doc/numpy/reference/ufuncs.html), which are essentially just mathematical operations you can use to perform the operation across the array. Let's show some common ones:

In [101]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [102]:
#Taking Square Roots
np.sqrt(arr)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ])

In [103]:
#Calcualting exponential (e^)
np.exp(arr)

array([1.00000000e+00, 2.71828183e+00, 7.38905610e+00, 2.00855369e+01,
       5.45981500e+01, 1.48413159e+02, 4.03428793e+02, 1.09663316e+03,
       2.98095799e+03, 8.10308393e+03])

In [104]:
# same as arr.max()
np.max(arr)

9

In [105]:
# there are many trigonometric functions
np.sin(arr)

array([ 0.        ,  0.84147098,  0.90929743,  0.14112001, -0.7568025 ,
       -0.95892427, -0.2794155 ,  0.6569866 ,  0.98935825,  0.41211849])

In [106]:
np.sin(np.pi/2)

1.0

In [107]:
np.tan(np.pi/4)

0.9999999999999999

In [108]:
np.log(arr)

array([      -inf, 0.        , 0.69314718, 1.09861229, 1.38629436,
       1.60943791, 1.79175947, 1.94591015, 2.07944154, 2.19722458])

In [109]:
np.log10(1000)

3.0

In [110]:
v

array([1, 2, 3, 4, 5])

In [111]:
np.subtract(v,1)

array([0, 1, 2, 3, 4])

In [112]:
x1=np.arange(9.0).reshape(3,3)
x2=np.arange(3.0)

In [113]:
x1

array([[0., 1., 2.],
       [3., 4., 5.],
       [6., 7., 8.]])

In [114]:
x2

array([0., 1., 2.])

In [115]:
np.subtract(x1,x2)

array([[0., 0., 0.],
       [3., 3., 3.],
       [6., 6., 6.]])

In [116]:
np.add(v,2)

array([3, 4, 5, 6, 7])

In [117]:
np.divide(v,2)

array([0.5, 1. , 1.5, 2. , 2.5])

In [118]:
np.multiply(v,4)

array([ 4,  8, 12, 16, 20])

In [119]:
# v**2
np.power(v,3)

array([  1,   8,  27,  64, 125])

In [120]:
# v % 2
np.mod(v,2)

array([1, 0, 1, 0, 1])

In [121]:
np.absolute(np.array([-9]))

array([9])

## Statistical Calculations

* ``np.mean(arr,axis=0)`` | Returns mean along specific axis

* ``arr.sum()`` | Returns sum of arr

* ``arr.min()`` | Returns minimum value of arr

* ``arr.max(axis=0)`` | Returns maximum value of specific axis

* ``np.var(arr)`` | Returns the variance of array

* ``np.std(arr,axis=1)`` | Returns the standard deviation of specific axis

* ``np.corrcoef(arr)`` | Returns correlation coefficient of array

In [122]:
v=np.array([1,1,2,2,3,3,3])
v

array([1, 1, 2, 2, 3, 3, 3])

In [123]:
np.mean(v)

2.142857142857143

In [124]:
np.median(v)

2.0

In [125]:
v.std()

0.8329931278350429

In [126]:
v.var()

0.6938775510204082

In [131]:
np.random.seed(42)
xarr = np.random.randn(3,3)
xarr

array([[ 0.49671415, -0.1382643 ,  0.64768854],
       [ 1.52302986, -0.23415337, -0.23413696],
       [ 1.57921282,  0.76743473, -0.46947439]])

In [132]:
np.corrcoef(xarr)

array([[ 1.        ,  0.33500663, -0.29669929],
       [ 0.33500663,  1.        ,  0.80039247],
       [-0.29669929,  0.80039247,  1.        ]])

# The End of the Session - 2

## You can take a look at an attractive [official tutorial](https://numpy.org/devdocs/user/absolute_beginners.html) for beginners of NumPy.